service: rss-feed

frameworkVersion: "3"
  
provider:
  name: aws
  profile: serhei
  stage: dev
  memorySize: 512
  runtime: nodejs18.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/rss-lambda
  environment:
    AWS_ACCOUNT_ID: ${aws:accountId}
    AWS_GATEWAY_ID: ${ssm:RSS_GATEWAY_API_ID}
    GOOGLE_CLIENT_ID: ${ssm:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${ssm:GOOGLE_CLIENT_SECRET}
    TOKEN_SECRET_KEY: ${ssm:TOKEN_SECRET_KEY}
    TELEGRAM_API_ID: ${ssm:TELEGRAM_API_ID}
    TELEGRAM_API_HASH: ${ssm:TELEGRAM_API_HASH}
    TELEGRAM_SESSION_KEY: ${ssm:TELEGRAM_SESSION_KEY}
    WEB_URL: ${ssm:RSS_WEB_URL}

functions:
  rss-sync-job:
    handler: services/rss-api/handlers/sync-job.handler
    events:
      - schedule: rate(1 hour)
  rss-get: 
    handler: services/rss-api/handlers/get.handler
  rss-create: 
    handler: services/rss-api/handlers/create.handler
  rss-sync: 
    handler: services/rss-api/handlers/sync.handler
  authentication: 
    handler: services/user-api/handlers/authentication.handler
  google-auth-url: 
    handler: services/user-api/handlers/google-auth/get-url.handler
  google-auth-webhook: 
    handler: services/user-api/handlers/google-auth/webhook.handler
  # local
  # get-telegram-session-key: 
  #   handler: services/local/get-session-key.handler