service: rss-feed

frameworkVersion: "3"
  
provider:
  name: aws
  profile: serhei
  stage: dev
  memorySize: 512
  runtime: nodejs18.x
  region: ${opt:region, "eu-north-1"}
  iam:
    role: arn:aws:iam::671661975001:role/rss-lambda
  environment: 
    SECRET_KEY: ${opt:stage, 'b6e889ef66b86b26accbb997e80ec0a81dbc137cd5835aeb10b63e4d333c9775'}

functions:
  user-auth:
    handler: services/user-api/handlers/authorization.handler
  rss-sync-job:
    handler: services/rss-api/handlers/sync-job.handler
    events:
      - schedule: rate(1 hour)
  rss-get: 
    handler: services/rss-api/handlers/get.handler
  rss-create: 
    handler: services/rss-api/handlers/create.handler
  rss-sync: 
    handler: services/rss-api/handlers/sync.handler
  authentication: 
    handler: services/user-api/handlers/authentication.handler
  # update-telegram-session-key: 
  #   handler: services/local/update-session-key.handler