service: rss-feed

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'eu-north-1'}
  environment: 
    SECRET_KEY: ${opt:stage, 'b6e889ef66b86b26accbb997e80ec0a81dbc137cd5835aeb10b63e4d333c9775'}

functions:
  authenticator:
    handler: functions/authenticator.handler
  update-session-key: 
    handler: functions/update-session-key.handler
  rss-sync:
    handler: functions/rss-sync.handler
    events:
      - schedule: rate(1 hour)
  channels:
    handler: functions/channels.handler